# Generated by Django 4.0.2 on 2022-02-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_columns',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='news_columns',
            name='content',
            field=models.TextField(blank=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='news_columns',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Опублековоно'),
        ),
        migrations.AlterField(
            model_name='news_columns',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Раздача'),
        ),
        migrations.AlterField(
            model_name='news_columns',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='news_columns',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='news_columns',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменино'),
        ),
    ]
