# Generated by Django 4.0.2 on 2022-02-21 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category_news_columns_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='news_columns',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='home.category', verbose_name='Категории'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news_columns',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Выбрано'),
        ),
    ]
